### ISSUE TITLE
Error: The report-json file "${report}" could not be resolved.

### ISSUE THREAD

**Issue by tcjeff** [ataylorme/eslint-annotate-action#39]
Hi guys.

The annotate action can't get generate a report.

`Error: The report-json file "${report}" could not be resolved.
(node:2180) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/runner/work/TPRun/TPRun/eslint_report.json'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.ESLintJsonReportToJS [as default] (/home/runner/work/_actions/ataylorme/eslint-annotate-action/1.2.0/dist/index.js:3917:41)
    at /home/runner/work/_actions/ataylorme/eslint-annotate-action/1.2.0/dist/index.js:4334:62
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/ataylorme/eslint-annotate-action/1.2.0/dist/index.js:43[12](https://github.com/tradersclub/TPRUN/runs/5681788923?check_suite_focus=true#step:6:12):71
    at new Promise (<anonymous>)
    at module.exports.355.__awaiter (/home/runner/work/_actions/ataylorme/eslint-annotate-action/1.2.0/dist/index.js:4308:12)
    at run (/home/runner/work/_actions/ataylorme/eslint-annotate-action/1.2.0/dist/index.js:4333:12)
    at Object.355 (/home/runner/work/_actions/ataylorme/eslint-annotate-action/1.2.0/dist/index.js:4463:1)
(node:2[18](https://github.com/tradersclub/TPRun/runs/5681788923?check_suite_focus=true#step:6:18)0) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:[21](https://github.com/tradersclub/TPRun/runs/5681788923?check_suite_focus=true#step:6:21)80) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by ataylorme** [comment]
Please check the file path
